
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liberaryproject;

/**
 *
 * @author amans
 */
public class LiberarianMenu extends javax.swing.JFrame {

    /**
     * Creates new form LiberarianMenu
     */
    public LiberarianMenu() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indiraPannel = new javax.swing.JPanel();
        indiraButton = new javax.swing.JButton();
        menuButton = new javax.swing.JPanel();
        javax.swing.JButton manageBooksButton = new javax.swing.JButton();
        manageStudentButton = new javax.swing.JButton();
        searchBooksButton = new javax.swing.JButton();
        manageBorrowerButton = new javax.swing.JButton();
        adminSettingButton = new javax.swing.JButton();
        generatereportButton = new javax.swing.JButton();
        generateBackupButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        indiraPannel.setBackground(new java.awt.Color(18, 49, 113));
        indiraPannel.setBorder(new javax.swing.border.MatteBorder(null));

        indiraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        indiraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiraButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indiraPannelLayout = new javax.swing.GroupLayout(indiraPannel);
        indiraPannel.setLayout(indiraPannelLayout);
        indiraPannelLayout.setHorizontalGroup(
            indiraPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiraPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indiraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        indiraPannelLayout.setVerticalGroup(
            indiraPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiraPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indiraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        menuButton.setBackground(new java.awt.Color(153, 255, 153));
        menuButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        manageBooksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Borrow_Book_50px.png"))); // NOI18N
        manageBooksButton.setText("Manage Books");
        manageBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBooksButtonActionPerformed(evt);
            }
        });

        manageStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Student_Male_50px.png"))); // NOI18N
        manageStudentButton.setText("Manage Students");
        manageStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentButtonActionPerformed(evt);
            }
        });

        searchBooksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_50px_1.png"))); // NOI18N
        searchBooksButton.setText("Search Books");
        searchBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBooksButtonActionPerformed(evt);
            }
        });

        manageBorrowerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_People_50px.png"))); // NOI18N
        manageBorrowerButton.setText("Manage Borrower");
        manageBorrowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBorrowerButtonActionPerformed(evt);
            }
        });

        adminSettingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Settings_50px.png"))); // NOI18N
        adminSettingButton.setText("Admin Setting");
        adminSettingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSettingButtonActionPerformed(evt);
            }
        });

        generatereportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Report_Card_50px.png"))); // NOI18N
        generatereportButton.setText("Generate Report");
        generatereportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatereportButtonActionPerformed(evt);
            }
        });

        generateBackupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Data_Backup_50px.png"))); // NOI18N
        generateBackupButton.setText("Generate Backup");
        generateBackupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBackupButtonActionPerformed(evt);
            }
        });

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Exit_50px.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuButtonLayout = new javax.swing.GroupLayout(menuButton);
        menuButton.setLayout(menuButtonLayout);
        menuButtonLayout.setHorizontalGroup(
            menuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuButtonLayout.createSequentialGroup()
                        .addComponent(manageBooksButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageBorrowerButton))
                    .addGroup(menuButtonLayout.createSequentialGroup()
                        .addComponent(adminSettingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generatereportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generateBackupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuButtonLayout.setVerticalGroup(
            menuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(menuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminSettingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generatereportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBackupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indiraPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(indiraPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generatereportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatereportButtonActionPerformed
        // TODO add your handling code here:
        GenerateReport generateReport=new  GenerateReport();
        generateReport.setVisible(true);
        
        //To close the current window when opens new
        LiberarianMenu liberarianMenu=new LiberarianMenu();
        liberarianMenu.setVisible(false);
        dispose();
    }//GEN-LAST:event_generatereportButtonActionPerformed

    private void generateBackupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBackupButtonActionPerformed
        // TODO add your handling code here:
        GenerateBackup generateBackup=new GenerateBackup();
        generateBackup.setVisible(true);
        
        //To close the current window when opens new
        LiberarianMenu liberarianMenu=new LiberarianMenu();
        liberarianMenu.setVisible(false);
        dispose();
    }//GEN-LAST:event_generateBackupButtonActionPerformed

    private void manageBorrowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBorrowerButtonActionPerformed
        // TODO add your handling code here:
        ManageBorrower manageBorrower=new ManageBorrower();
        manageBorrower.setVisible(true);
        
        //To close the current window when opens new
        LiberarianMenu liberarianMenu=new LiberarianMenu();
        liberarianMenu.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_manageBorrowerButtonActionPerformed

    private void searchBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBooksButtonActionPerformed
        // TODO add your handling code here:
        SearchBooks searchBooks=new SearchBooks();
        searchBooks.setVisible(true);
        
        //To close the current window when opens new
        LiberarianMenu liberarianMenu=new LiberarianMenu();
        liberarianMenu.setVisible(false);
        dispose();
    }//GEN-LAST:event_searchBooksButtonActionPerformed

    private void manageBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBooksButtonActionPerformed
        // TODO add your handling code here:
        ManageBooks manageBooks=new ManageBooks();
        manageBooks.setVisible(true);
        
        //To close the current window when opens new
        LiberarianMenu liberarianMenu=new LiberarianMenu();
        liberarianMenu.setVisible(false);
        dispose();
    }//GEN-LAST:event_manageBooksButtonActionPerformed

    private void manageStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentButtonActionPerformed
        // TODO add your handling code here:
        ManageStudents manageStudents=new ManageStudents();
        manageStudents.setVisible(true);
        
        //To close the current window when opens new
        LiberarianMenu liberarianMenu=new LiberarianMenu();
        liberarianMenu.setVisible(false);
        dispose();
    }//GEN-LAST:event_manageStudentButtonActionPerformed

    private void indiraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiraButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indiraButtonActionPerformed

    private void adminSettingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSettingButtonActionPerformed
        // TODO add your handling code here:
        AdminSettings adminSettings=new AdminSettings();
        adminSettings.setVisible(true);
        
        //To close the current window when opens new
        LiberarianMenu liberarianMenu=new LiberarianMenu();
        liberarianMenu.setVisible(false);
        dispose();
    }//GEN-LAST:event_adminSettingButtonActionPerformed

private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed


    Welcome welcome = new Welcome();
    welcome.setVisible(true);
    
    LiberarianMenu liberarianMenu;
        liberarianMenu = new LiberarianMenu();
    liberarianMenu.setVisible(false);
    dispose();
}//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiberarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiberarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiberarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiberarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LiberarianMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminSettingButton;
    private javax.swing.JButton generateBackupButton;
    private javax.swing.JButton generatereportButton;
    private javax.swing.JButton indiraButton;
    private javax.swing.JPanel indiraPannel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageBorrowerButton;
    private javax.swing.JButton manageStudentButton;
    private javax.swing.JPanel menuButton;
    private javax.swing.JButton searchBooksButton;
    // End of variables declaration//GEN-END:variables
}
