/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liberaryproject;

/**
 *
 * @author amans
 */
public class ManageBooks extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    public ManageBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indiraPannel = new javax.swing.JPanel();
        indiraButtom = new javax.swing.JButton();
        menuPannel = new javax.swing.JPanel();
        addNewBookButton = new javax.swing.JButton();
        listOfBookbutton = new javax.swing.JButton();
        editBookInfoButton = new javax.swing.JButton();
        bookRequestButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        indiraPannel.setBackground(new java.awt.Color(18, 49, 113));
        indiraPannel.setToolTipText("");

        indiraButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        indiraButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiraButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indiraPannelLayout = new javax.swing.GroupLayout(indiraPannel);
        indiraPannel.setLayout(indiraPannelLayout);
        indiraPannelLayout.setHorizontalGroup(
            indiraPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiraPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indiraButtom, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        indiraPannelLayout.setVerticalGroup(
            indiraPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiraPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indiraButtom, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPannel.setBackground(new java.awt.Color(153, 255, 153));
        menuPannel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addNewBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Health_Book_50px.png"))); // NOI18N
        addNewBookButton.setText("Add New Book");
        addNewBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBookButtonActionPerformed(evt);
            }
        });

        listOfBookbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Ingredients_List_50px.png"))); // NOI18N
        listOfBookbutton.setText("List of Books");
        listOfBookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfBookbuttonActionPerformed(evt);
            }
        });

        editBookInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bookmark_50px.png"))); // NOI18N
        editBookInfoButton.setText("Edit Book Info");
        editBookInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookInfoButtonActionPerformed(evt);
            }
        });

        bookRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Book_Shelf_50px.png"))); // NOI18N
        bookRequestButton.setText("Books Request");
        bookRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPannelLayout = new javax.swing.GroupLayout(menuPannel);
        menuPannel.setLayout(menuPannelLayout);
        menuPannelLayout.setHorizontalGroup(
            menuPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPannelLayout.createSequentialGroup()
                        .addComponent(addNewBookButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(listOfBookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPannelLayout.createSequentialGroup()
                        .addComponent(editBookInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(bookRequestButton)))
                .addContainerGap())
        );
        menuPannelLayout.setVerticalGroup(
            menuPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listOfBookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(menuPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBookInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleLabel.setText("Manage Books");

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_25px.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indiraPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(menuPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(579, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 683, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(indiraPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel)
                .addGap(26, 26, 26)
                .addComponent(menuPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indiraButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiraButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indiraButtomActionPerformed

    private void addNewBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBookButtonActionPerformed

        AddNewBook addNewBook=new AddNewBook();
        addNewBook.setVisible(true);
        
        //To close the current window and opens new
        ManageBooks manageBooks=new ManageBooks();
        manageBooks.setVisible(false);
        dispose();
    }//GEN-LAST:event_addNewBookButtonActionPerformed

    private void editBookInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookInfoButtonActionPerformed
        
        EditBookInfo editBookInfo=new EditBookInfo();
        editBookInfo.setVisible(true);
        
        //To close the current window and opens new
        ManageBooks manageBooks=new ManageBooks();
        manageBooks.setVisible(false);
        dispose();
    }//GEN-LAST:event_editBookInfoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        LiberarianMenu liberarianMenu=new LiberarianMenu();
        liberarianMenu.setVisible(true);
        
        //To close the current window and opens new
        ManageBooks manageBooks=new ManageBooks();
        manageBooks.setVisible(false);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

private void listOfBookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfBookbuttonActionPerformed
    
    ListofBooks listofBooks=new ListofBooks();
    listofBooks.setVisible(true);
    
    //To close the current window and opens new
        ManageBooks manageBooks=new ManageBooks();
        manageBooks.setVisible(false);
        dispose();
}//GEN-LAST:event_listOfBookbuttonActionPerformed

private void bookRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRequestButtonActionPerformed

   BookRequest bookRequest=new BookRequest();
   bookRequest.setVisible(true);
   
   //To close the current window and opens new
        ManageBooks manageBooks=new ManageBooks();
        manageBooks.setVisible(false);
        dispose();
}//GEN-LAST:event_bookRequestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManageBooks().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewBookButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookRequestButton;
    private javax.swing.JButton editBookInfoButton;
    private javax.swing.JButton indiraButtom;
    private javax.swing.JPanel indiraPannel;
    private javax.swing.JButton listOfBookbutton;
    private javax.swing.JPanel menuPannel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
}
